# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: XplatGenerateReleaseNotes@4
  inputs:
    outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
    templateLocation: 'File'
    templatefile: 'ReleaseNotesTemplate.md'
    dumpPayloadToConsole: false
    dumpPayloadToFile: false
    replaceFile: false
    appendtofile: false
    getParentsAndChildren: False
    getAllParents: False
    getIndirectPullRequests: False
    stopOnError: False
    considerPartiallySuccessfulReleases: False
    checkForManuallyLinkedWI: False
    wiqlFromTarget: 'WorkItems'
    bitbucketSecret: 

- task: WikiUpdaterTask@3
  inputs:
    repo: 'https://AngryTroll@dev.azure.com/AngryTroll/BlazorDemo/_git/BlazorDemo.wiki'
    filename: 'Release Notes'
    replaceFile: True
    dataIsFile: true
    sourceFile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
    message: 'release note update'
    gitname: 'release'
    gitemail: 'jay.gilesuk68@gmail.com'
    localpath: '$(System.DefaultWorkingDirectory)\repo'
    RetryMode: 'Pull'
